import type { Metadata } from "next";
import { Rowdies } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import { AnimatePresence } from "motion/react";

const rowdies = Rowdies({
    weight: ["300", "400", "700"],
    style: "normal",
});

export const metadata: Metadata = {
    title: "Suash Media",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <AnimatePresence>
            <html lang="es">
                <body className={`${rowdies.className}`}>
                    <Navbar />
                    {children}
                </body>
            </html>
        </AnimatePresence>
    );
}
