import type { Metadata } from "next";
import "./globals.css";
import LayoutComponent from "@/components/LayoutComponent";

export const metadata: Metadata = {
    title: "Suash Media",
    description: "Generated by create next app",
}; 

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="es">
            <LayoutComponent>{children}</LayoutComponent>
        </html>
    );
}
