import type { Metadata } from "next";
import "./globals.css";
import LayoutComponent from "@/components/LayoutComponent";
import StyledComponentsRegistry from "@/lib/registry";

export const metadata: Metadata = {
    title: "Suash Media",
    description: "Generated by create next app",
    icons: [
        {
            url: "/favicon.ico",
            rel: "icon",
            sizes: "16x16",
        },
    ],
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="es">
            <StyledComponentsRegistry>
                <LayoutComponent>{children}</LayoutComponent>
            </StyledComponentsRegistry>
        </html>
    );
}
